version: "3.2"

services:
  adminer:
    container_name: adminer
    build:
      context: ${HUNCHO_DIR}/services/adminer
      dockerfile: ${HUNCHO_DIR}/services/adminer/build/Dockerfile
    restart: always
    ports:
      - 8090:8080
  contest:
    container_name: contest
    build:
      context: ${HUNCHO_DIR}/services/contest
      dockerfile: ${HUNCHO_DIR}/services/contest/build/Dockerfile.test
    restart: on-failure
    volumes:
      - ${HUNCHO_DIR}/services/contest/migrations:/home/app/migrations
      - ${HUNCHO_DIR}/services/contest/bin:/home/app/bin
      - ${HUNCHO_DIR}/services/contest/tests:/home/app/tests
      - ${HUNCHO_DIR}/services/contest/seeds:/home/app/seeds
      - ${HUNCHO_DIR}/services/contest/src:/home/app/src
      - ${HUNCHO_DIR}/services/contest/statics:/home/app/statics
      - ${HUNCHO_DIR}/services/contest/manage.py:/home/app/manage.py
      - ${HUNCHO_DIR}/services/contest/setup.py:/home/app/setup.py
    env_file:
      - ${HUNCHO_DIR}/env/test/.env.contest
      - ${HUNCHO_DIR}/secrets/s3/credentials.txt
    healthcheck:
      test: curl --fail -s contest:5000/ping || exit 1
      interval: 60s
      timeout: 5s
      retries: 5
    depends_on:
#      - contest_cache
      - contest_db
#  contest_cache:
#    container_name: contest_cache
#    build:
#      context: ${HUNCHO_DIR}/services/redis
#      dockerfile: ${HUNCHO_DIR}/services/redis/build/Dockerfile
#    restart: unless-stopped
#    volumes:
#      - ${HUNCHO_DIR}/data/test/contest_cache/redis_data:/var/libs/redis
#      - ${HUNCHO_DIR}/data/test/contest_cache/redis.conf:/usr/local/etc/redis/redis.conf
#    env_file:
#      - ${HUNCHO_DIR}/env/test/.env.contest_cache
#    healthcheck:
#      test: ["CMD", "redis-cli","ping"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
  contest_db:
    container_name: contest_db
    build:
      context: ${HUNCHO_DIR}/services/postgresql
      dockerfile: ${HUNCHO_DIR}/services/postgresql/build/Dockerfile
      args:
        POSTGRES_VERSION: 9.6
    ports:
      - 5432:5432
    volumes:
      - ${HUNCHO_DIR}/data/test/contest_db/data:/var/libs/postgresql/data/
    env_file:
      - ${HUNCHO_DIR}/env/test/.env.contest_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U contest"]
      interval: 10s
      timeout: 5s
      retries: 20
  contest_proxy:
    container_name: contest_proxy
    build:
      context: ${HUNCHO_DIR}/services/contest/proxy
      dockerfile: ${HUNCHO_DIR}/services/contest/proxy/build/Dockerfile
    restart: on-failure
    volumes:
      - ${HUNCHO_DIR}/services/contest/statics/.:/usr/share/nginx/
    ports:
      - 80:80
    depends_on:
      - contest