version: "3.2"

services:
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - 8070:8080
    networks:
      - app-net
  contest:
    container_name: contest
    build:
      context: ${HUNCHO_DIR}/services/contest
      dockerfile: ${HUNCHO_DIR}/services/contest/build/Dockerfile
    restart: on-failure
    volumes:
      - ${HUNCHO_DIR}/services/contest/migrations:/home/app/migrations
      - ${HUNCHO_DIR}/services/contest/bin:/home/app/bin
      - ${HUNCHO_DIR}/services/contest/tests:/home/app/tests
      - ${HUNCHO_DIR}/services/contest/seeds:/home/app/seeds
      - ${HUNCHO_DIR}/services/contest/src:/home/app/src
      - ${HUNCHO_DIR}/services/contest/logs:/home/app/logs
      - ${HUNCHO_DIR}/services/contest/statics:/home/app/statics
      - ${HUNCHO_DIR}/services/contest/manage.py:/home/app/manage.py
      - ${HUNCHO_DIR}/services/contest/setup.py:/home/app/setup.py
    ports:
      - 20001:5000
    env_file:
      - env/.env.contest
      - ${HUNCHO_DIR}/secrets/s3/credentials.txt
    healthcheck:
      test: curl --fail -s contest:5000/ping || exit 1
      interval: 300s
      timeout: 5s
      retries: 5
    depends_on:
      - contest_cache
      - contest_db
    networks:
      - app-net
  contest_cache:
    container_name: contest_cache
    image: redis:6
    restart: unless-stopped
    volumes:
      - contest_cache:/var/libs/redis
    env_file:
      - env/.env.contest_cache
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-net
  contest_db:
    container_name: contest_db
    image: postgres:9.6
    volumes:
      - contest_data:/var/libs/postgresql/data/
    env_file:
      - env/.env.contest_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U contest" ]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - app-net
  contest_kafka:
    container_name: contest_kafka
    image: wurstmeister/kafka:latest
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - env/.env.contest_kafka
    depends_on:
      - contest_zookeeper
    networks:
      - app-net
  contest_zookeeper:
    container_name: contest_zookeeper
    image: wurstmeister/zookeeper:latest
    restart: on-failure
    env_file:
      - env/.env.contest_zookeeper
    networks:
      - app-net
  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    ports:
      - 8082:8081
    env_file:
      - env/.env.contest-redis-commander
    depends_on:
      - contest_cache
    networks:
      - app-net
volumes:
  contest_data:
  contest_cache:
networks:
  app-net:
    driver: bridge
